server:
  ip: '127.0.0.1'
  origin: ['blyberg.net']

db:
  host: ['localhost']
  username: 'dbusername'
  password: 'dbpassword'
  synchronize: false

jwt:
  secret: 'jwtsecret'

nodemailer:
  user: 'someone@somewhere.net'
  password: 'emailpassword'
